#!/bin/csh -f
################################################################################
# Combined simulation top script by Goutam Krapa 2215855
# Change modelsim directory in this file and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# Check if current dir has ModelSim config file
set has_config  [file exists modelsim.do]
# Configure ModelSim
if {$has_config==1} { do modelsim.do ; }

echo "+====================================="
echo "| Create Library Work soc            "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Compile RTL Code of soc            "
echo "+====================================="

# Compile both Mealy and Moore testbenches
vlog -v ../dut/seq_det_101_mealy_b.v  ../tb/tb_seq_det_101_melay.v
vlog -v ../dut/seq_det_101_moore_b.v  ../tb/tb_seq_det_101_moore.v

echo "+====================================="
echo "| Compiler Pass                      "
echo "| Beginning Simulation                "
echo "+====================================="

# Simulate Mealy testbench
vsim work.tb_seq_det_101_melay -t 1ns

# Add Waveform Signals for Mealy FSM
echo "+====================================="
echo "| Adding Waveform Signals for Mealy   "
echo "+====================================="
add wave -noupdate -format logic -radix hexadecimal tb_seq_det_101_melay/clk
add wave -noupdate -format logic -radix hexadecimal tb_seq_det_101_melay/rst
add wave -noupdate -format logic -radix binary tb_seq_det_101_melay/x
add wave -noupdate -format logic -radix binary -color cyan tb_seq_det_101_melay/y;
add wave -noupdate -format logic -radix hexadecimal -color blue tb_seq_det_101_melay/mealy_fsm/cur_state
add wave -noupdate -format logic -radix hexadecimal -color blue tb_seq_det_101_melay/mealy_fsm/nxt_state

# Run simulation for Mealy
run 600ns

# Now, run the Moore testbench
# Note: This will keep the previous simulation window open
vsim work.tb_seq_det_101_moore -t 1ns

# Add Waveform Signals for Moore FSM
echo "+====================================="
echo "| Adding Waveform Signals for Moore    "
echo "+====================================="
add wave -noupdate -format logic -radix hexadecimal tb_seq_det_101_moore/clk
add wave -noupdate -format logic -radix hexadecimal tb_seq_det_101_moore/rst
add wave -noupdate -format logic -radix binary tb_seq_det_101_moore/x
add wave -noupdate -format logic -radix binary -color yellow tb_seq_det_101_moore/y;
add wave -noupdate -format logic -radix hexadecimal -color green tb_seq_det_101_moore/moore_fsm/cur_state
add wave -noupdate -format logic -radix hexadecimal -color green tb_seq_det_101_moore/moore_fsm/nxt_state

# Run simulation for Moore
run 600ns

# End of script
echo "+====================================="
echo "| Simulation Complete                 "
echo "+====================================="