#!/bin/csh -f
################################################################################
# simulation top script by Goutam Krapa 2215855
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="

#vlog -f ../filelist/filelist.f
# Alternative manual compilation if filelist not available:
vlog -v ../dut/seq_det_101_moore_b.v  ../tb/tb_seq_det_101_moore.v

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.tb_seq_det_101_moore -t 1ns

################## #################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal tb_seq_det_101_moore/clk
add wave -noupdate -format logic -radix hexadecimal tb_seq_det_101_moore/rst
add wave -noupdate -format logic -radix binary tb_seq_det_101_moore/x
add wave -noupdate -format logic -radix binary -color yellow tb_seq_det_101_moore/y;
add wave -noupdate -format logic -radix hexadecimal -color green tb_seq_det_101_moore/moore_fsm/cur_state
add wave -noupdate -format logic -radix hexadecimal -color green tb_seq_det_101_moore/moore_fsm/nxt_state


run 200ns

##possible colors of waveform black
#white
#red
#green
#blue
#yellow
#cyan
#magenta