#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="

vlog -f ../filelist/filelist.f  
##or##vlog -v ../dut/and_or.v ../tb/tb_and_or_reg.v
##vlog -v ../dut/and_or_reg.v ../tb/tb_and_or_reg.v

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.tb_and_or_reg -t 1ns

################## #################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal tb_and_or_reg/clk
add wave -noupdate -format logic -radix hexadecimal tb_and_or_reg/a
add wave -noupdate -format logic -radix hexadecimal tb_and_or_reg/b
add wave -noupdate -format logic -radix hexadecimal tb_and_or_reg/c
add wave -noupdate -format logic -radix hexadecimal tb_and_or_reg/d
add wave -noupdate -format logic -radix hexadecimal tb_and_or_reg/rst
add wave -noupdate -format logic -radix hexadecimal tb_and_or_reg/f

add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or_reg/uut/clk
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or_reg/uut/a
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or_reg/uut/b
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or_reg/uut/c
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or_reg/uut/d
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or_reg/uut/rst
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or_reg/uut/e
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or_reg/uut/f
run 200ns                                                                            
