#!/bin/csh -f
################################################################################
# simulation top script by Goutam Krapa 2215855
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="

vlog +define+MOORE\
	-f ../filelist/filelist_moore.f
#vlog -f ../filelist/filelist.f
# Alternative manual compilation if filelist not available:
##vlog -v ../dut/seq_det_101_moore_b.v  ../tb/tb_seq_det_101.v

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.tb_seq_det_101 -t 1ns

################## #################### mus  ####################################
add wave -noupdate tb_seq_det_101/clk
add wave -noupdate tb_seq_det_101/rst
add wave -noupdate tb_seq_det_101/x
add wave -noupdate tb_seq_det_101/y
add wave -noupdate -color blue tb_seq_det_101/u_seq_det_101_moore/cur_state
add wave -noupdate -color blue tb_seq_det_101/u_seq_det_101_moore/nxt_state


run 350ns

##possible colors of waveform black
#white
#red
#green
#blue
#yellow
#cyan
#magenta