#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="

vlog -f ../filelist/filelist.f  
##or##vlog -v ../dut/and_or.v ../tb/tb_and_or.v

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.tb_and_or -t 1ns

################## #################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal tb_and_or/aa
add wave -noupdate -format logic -radix hexadecimal tb_and_or/bb
add wave -noupdate -format logic -radix hexadecimal tb_and_or/cc
add wave -noupdate -format logic -radix hexadecimal tb_and_or/ddd
add wave -noupdate -format logic -radix hexadecimal tb_and_or/ee

add wave -noupdate -format logic -radix decimal tb_and_or/i

add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or/u_and_or/a
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or/u_and_or/b
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or/u_and_or/c
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or/u_and_or/d
add wave -noupdate -format logic -radix hexadecimal -color blue tb_and_or/u_and_or/e
run 200ns                                                                            
